# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Room9 FrontEnd CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build Docker Image
      env:
        BUILD_NUMBER: ${{ github.run_number }}
      run: |
        IMAGE_NAME=labyu/room9-frontend:$BUILD_NUMBER
        docker build -t $IMAGE_NAME ./
        docker push $IMAGE_NAME
