# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Room9 FrontEnd CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build Docker Image
      env:
        BUILD_NUMBER: ${{ github.run_number }}
      run: |
        IMAGE_NAME=labyu/room9-frontend:$BUILD_NUMBER
        docker build -t $IMAGE_NAME ./
        docker push $IMAGE_NAME

    - uses: AutoModality/action-clean@v1
    - name: Checkout Infra Repo
      env:
        INFRA_KEY: ${{ secrets.ROOM9_INFRA_KEY }}
      run: |
        rm * -rf
        rm -rf .git
        eval `ssh-agent -s`
        ssh-add - <<< "${INFRA_KEY}"; git clone git@github.com:Hanium-Cloud/room9-infra.git .
    - name: Change Deploy Spec
      env:
        BUILD_NUMBER: ${{ github.run_number }}
      run: |
        IMAGE_NAME=labyu/room9-frontend
        cd frontend
        BEFORE=$(cat room9-frontend.yaml | grep 'image: labyu/room9-frontend:' | sed -e 's/^ *//g' -e 's/ *$//g')
        sed -i "s@$BEFORE@image: labyu/room9-frontend:$BUILD_NUMBER@g" room9-frontend.yaml

        git config user.name labyu
        git config user.email labyu2020@gmail.com
        git add .
        git commit -m "Action Change Deployment Spec To image: labyu/room9-frontend:$BUILD_NUMBER"
        git push origin main
